#!/bin/sh
set -e

if [ -z "$1" ]; then
  echo "Usage: bump <version>"
  exit 1
fi

# Trim leading "v"
VERSION=${1#v}

echo "bump $VERSION"

sed -i "4c Version: v$VERSION" README.md
sed -i "4c 版本：v$VERSION" README.zh-CN.md
echo "v$VERSION" >VERSION

go run -C tools . "$VERSION"
